version: "3.8"

# Docker Compose für lokale Entwicklung mit Docker Desktop
# Verwendung: docker-compose -f docker-compose.dev.yml up --build

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_USER=guestuser
      - DB_PASSWORD=whHBJveMvwjs5a6p
      - DB_NAME=guestbook
      - JWT_SECRET_KEY=DeRBC3FDeY8d9nw9WMBwNJ0LpVyvB5ty607r2PHdmQBpqn
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=support@dcng.de
      - ADMIN_PASSWORD=whHBJveMvwjs5a6p
      - ADMIN_IS_SUPERUSER=true # true/false - Ob der Admin Superuser-Rechte haben soll
      - ADMIN_ROLE=superuser # moderator/admin/superuser - Spezifische Rolle
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - guestbook-network
    # Development: Hot reload
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - guestbook-network
    # Development: Hot reload
    stdin_open: true
    tty: true

  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=Kx9mP2vR8nQ5wE7tY3uI6oL1sA4hG9jB
      - MYSQL_DATABASE=guestbook
      - MYSQL_USER=guestuser
      - MYSQL_PASSWORD=whHBJveMvwjs5a6p
    volumes:
      - db_data_dev:/var/lib/mysql
    ports:
      - "3306:3306" # Für lokale DB-Verbindungen
    networks:
      - guestbook-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Optional: phpMyAdmin für lokale DB-Verwaltung
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_USER=guestuser
      - PMA_PASSWORD=whHBJveMvwjs5a6p
      - MYSQL_ROOT_PASSWORD=Kx9mP2vR8nQ5wE7tY3uI6oL1sA4hG9jB
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - guestbook-network

volumes:
  db_data_dev:
    driver: local
  backend_uploads:
    driver: local

networks:
  guestbook-network:
    driver: bridge
