version: '3.8'

# Portainer Stack für UGreen NAS Deployment
# Verwendet GHCR.io Images für Production

services:
  backend:
    image: ghcr.io/baronblk/guestbook-project/backend:latest
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_USER=guestuser
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=guestbook
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - backend_uploads:/app/uploads
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    depends_on:
      - db
    networks:
      - guestbook-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: ghcr.io/baronblk/guestbook-project/frontend:latest
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    depends_on:
      - backend
    networks:
      - guestbook-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'

  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=guestbook
      - MYSQL_USER=guestuser
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_INITDB_SKIP_TZINFO=1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - guestbook-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "guestuser", "-p${DB_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: >
      --innodb-buffer-pool-size=256M
      --max-connections=100
      --query-cache-size=32M
      --query-cache-type=1

volumes:
  db_data:
    driver: local
  backend_uploads:
    driver: local

networks:
  guestbook-network:
    driver: bridge

# Environment Variables für Portainer Stack:
# Setze diese in Portainer unter "Environment variables"
#
# DB_PASSWORD=your-secure-db-password-here
# MYSQL_ROOT_PASSWORD=your-secure-root-password-here
# JWT_SECRET_KEY=your-super-secret-jwt-key-change-in-production
# ADMIN_USERNAME=admin
# ADMIN_EMAIL=admin@guestbook.local
# ADMIN_PASSWORD=your-secure-admin-password-here
# REACT_APP_API_URL=http://YOUR-UGREEN-NAS-IP:8000
# FRONTEND_PORT=3000
# BACKEND_PORT=8000
