version: "3.8"

services:
  db:
    image: mariadb:11
    container_name: guestbook-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-secure_root_password}
      MYSQL_DATABASE: ${DB_NAME:-guestbook}
      MYSQL_USER: ${DB_USER:-guestbook_user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secure_password}
    volumes:
      - guestbook_db_data:/var/lib/mysql
    networks:
      - guestbook-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    image: ghcr.io/${GITHUB_REPOSITORY:-baronblk/guestbook-project}/guestbook-backend:${IMAGE_TAG:-latest}
    container_name: guestbook-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Database
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${DB_NAME:-guestbook}
      DB_USER: ${DB_USER:-guestbook_user}
      DB_PASSWORD: ${DB_PASSWORD:-secure_password}

      # Admin User
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
      ADMIN_IS_SUPERUSER: ${ADMIN_IS_SUPERUSER:-true}

      # Security
      SECRET_KEY: ${SECRET_KEY:-your-super-secret-key-change-in-production}
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret-change-in-production}

      # API Settings
      API_CORS_ORIGINS: ${API_CORS_ORIGINS:-http://localhost,http://localhost:3000,http://localhost:80}

    volumes:
      - guestbook_uploads:/app/uploads
    networks:
      - guestbook-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY:-baronblk/guestbook-project}/guestbook-frontend:${IMAGE_TAG:-latest}
    container_name: guestbook-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-80}:80"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:8000}
    networks:
      - guestbook-network

volumes:
  guestbook_db_data:
    driver: local
  guestbook_uploads:
    driver: local

networks:
  guestbook-network:
    driver: bridge
