version: "3.9"

services:
  db:
    image: mariadb:11
    restart: unless-stopped
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: Kx9mP2vR8nQ5wE7tY3uI6oL1sA4hG9jB
      MYSQL_DATABASE: guestbook
      MYSQL_USER: guestuser
      MYSQL_PASSWORD: whHBJveMvwjs5a6p
      # Korrigierte MariaDB-Variablen
      MARIADB_ROOT_PASSWORD: Kx9mP2vR8nQ5wE7tY3uI6oL1sA4hG9jB
      MARIADB_DATABASE: guestbook
      MARIADB_USER: guestuser
      MARIADB_PASSWORD: whHBJveMvwjs5a6p
      # Produktionsoptimierungen
      MARIADB_INNODB_BUFFER_POOL_SIZE: 256M
      MARIADB_INNODB_LOG_FILE_SIZE: 64M
      # Auto-Init
      MARIADB_AUTO_UPGRADE: 1
    volumes:
    # Hauptdatenbank (persistent) - Korrigierter Pfad
    - guestbook-db-data:/var/lib/mysql
    # Backup-Volume für automatische Backups
    - guestbook-backup-data:/backups
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-pKx9mP2vR8nQ5wE7tY3uI6oL1sA4hG9jB" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
    - guestbook-network
    labels:
    - "com.centurylinklabs.watchtower.enable=false" # DB nicht automatisch updaten

  app:
    image: ghcr.io/baronblk/guestbook-project/combined:2.0.1
    restart: unless-stopped
    platform: linux/amd64
    ports:
    - "3000:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: guestuser
      DB_PASSWORD: whHBJveMvwjs5a6p
      DB_NAME: guestbook
      JWT_SECRET_KEY: DeRBC3FDeY8d9nw9WMBwNJ0LpVyvB5ty607r2PHdmQBpqn
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: support@dcng.de
      ADMIN_PASSWORD: whHBJveMvwjs5a6p
      # Produktionsumgebung
      NODE_ENV: production
      LOG_LEVEL: info
      # Frontend API URL Konfiguration
      REACT_APP_API_URL: ""
      # Backend CORS Konfiguration
      ALLOWED_ORIGINS: "*"
    volumes:
    # Upload-Dateien (persistent)
    - guestbook-upload-data:/app/uploads
    # Logs (persistent)
    - guestbook-logs-data:/app/logs
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
    - guestbook-network
    labels:
    - "com.centurylinklabs.watchtower.enable=true" # App automatisch updaten

networks:
  guestbook-network:
    driver: bridge

volumes:
  guestbook-db-data:
    driver: local
  guestbook-upload-data:
    driver: local
  guestbook-logs-data:
    driver: local
  guestbook-backup-data:
    driver: local
