version: "3.9"

services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: Kx9mP2vR8nQ5wE7tY3uI6oL1sA4hG9jB
      MARIADB_DATABASE: guestbook
      MARIADB_USER: guestuser
      MARIADB_PASSWORD: whHBJveMvwjs5a6p
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: ghcr.io/baronblk/guestbook-project/combined:2.0.1
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: guestuser
      DB_PASSWORD: whHBJveMvwjs5a6p
      DB_NAME: guestbook
      JWT_SECRET_KEY: DeRBC3FDeY8d9nw9WMBwNJ0LpVyvB5ty607r2PHdmQBpqn
      ADMIN_USERNAME: admin
      ADMIN_EMAIL: support@dcng.de
      ADMIN_PASSWORD: whHBJveMvwjs5a6p
    volumes:
      - uploads_data:/app/uploads

volumes:
  db_data:
  uploads_data:
